# Generated by Django 2.2.3 on 2019-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=50)),
                ('server', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(max_length=150)),
                ('cpu_mf', models.IntegerField()),
                ('memoria_mf', models.IntegerField()),
                ('disco', models.IntegerField()),
                ('tipo_maq', models.CharField(max_length=20)),
                ('cpu_mv', models.IntegerField()),
                ('memoria_mv', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('perfil', models.CharField(max_length=20)),
                ('recurso', models.CharField(max_length=20)),
                ('valor_tabela', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proc_adicional', models.IntegerField()),
                ('valor_proc_adicional', models.DecimalField(decimal_places=2, max_digits=5)),
                ('memoria_adicional', models.IntegerField()),
                ('valor_memoria_adicional', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disco_adicional', models.IntegerField()),
                ('valor_disco_adicional', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
    ]
