# Generated by Django 2.2.3 on 2019-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='descricao',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='empresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='server',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_disco_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_memoria_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_proc_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
