# Generated by Django 2.2.3 on 2019-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_auto_20190717_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='valor_disco_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_memoria_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_proc_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_tabela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
