# Generated by Django 2.2.3 on 2019-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_auto_20190717_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosting',
            old_name='cpu_mf',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='hosting',
            old_name='cpu_mv',
            new_name='memoria',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='memoria_mf',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='memoria_mv',
        ),
        migrations.AlterField(
            model_name='hosting',
            name='recurso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='tipo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='tipo_maq',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
