# Generated by Django 2.2.3 on 2019-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_servicos_adicionais_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('valorUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('quantidade', models.IntegerField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
