# Generated by Django 2.2.3 on 2019-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_backup_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_dados',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
