# Generated by Django 2.2.3 on 2019-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0010_auto_20190725_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_dados',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
