# Generated by Django 2.2.3 on 2019-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0011_auto_20190725_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_dados',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
