# Generated by Django 2.2.3 on 2019-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0012_auto_20190725_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_dados',
            name='valorUnitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='disco',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='disco_adicional',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='memoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='memoria_adicional',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='proc_adicional',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
