# Generated by Django 2.2.3 on 2019-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0014_auto_20190725_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_dados',
            name='hosting_fieb',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hosting FIEB'),
        ),
        migrations.AddField(
            model_name='backup_dados',
            name='hosting_senai',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hosting SENAI'),
        ),
        migrations.AddField(
            model_name='servicos_adicionais',
            name='hosting_fieb',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hosting FIEB'),
        ),
        migrations.AddField(
            model_name='servicos_adicionais',
            name='hosting_senai',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hosting SENAI'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='hosting_fieb',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hosting FIEB'),
        ),
    ]
