# Generated by Django 2.2.3 on 2019-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0015_auto_20190726_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='cpu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='memoria',
            field=models.PositiveIntegerField(default=0, verbose_name='Memória'),
        ),
    ]
