# Generated by Django 2.2.3 on 2019-07-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0016_auto_20190726_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup_dados',
            name='hosting_fieb',
        ),
        migrations.RemoveField(
            model_name='backup_dados',
            name='hosting_senai',
        ),
        migrations.RemoveField(
            model_name='servicos_adicionais',
            name='hosting_fieb',
        ),
        migrations.RemoveField(
            model_name='servicos_adicionais',
            name='hosting_senai',
        ),
    ]
