# Generated by Django 2.2.3 on 2019-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0017_auto_20190726_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
