# Generated by Django 2.2.3 on 2019-07-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0019_financeiro_tabela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financeiro',
        ),
        migrations.AddField(
            model_name='hosting',
            name='mes',
            field=models.DateField(auto_now=True),
        ),
    ]
