# Generated by Django 2.2.3 on 2019-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0020_auto_20190729_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.CharField(max_length=200)),
            ],
        ),
    ]
