# Generated by Django 2.2.3 on 2019-07-30 13:08

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0026_auto_20190730_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json',
            name='json',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
