# Generated by Django 2.2.3 on 2019-07-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0027_auto_20190730_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='mes',
            field=models.CharField(default='July', max_length=12),
        ),
    ]
