# Generated by Django 2.2.3 on 2019-07-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0028_auto_20190730_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Json',
        ),
    ]
