# Generated by Django 2.2.3 on 2019-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0029_delete_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='teste',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
