# Generated by Django 2.2.3 on 2019-07-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0030_hosting_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='teste',
        ),
    ]
