# Generated by Django 2.2.3 on 2019-07-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0033_financeiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financeiro',
        ),
    ]
