# Generated by Django 2.2.3 on 2019-07-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0036_auto_20190730_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting_deleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='Descrição')),
                ('cpu', models.PositiveIntegerField(default=0)),
                ('memoria', models.PositiveIntegerField(default=0, verbose_name='Memória')),
                ('disco', models.IntegerField(default=0)),
                ('tipo_maq', models.CharField(blank=True, max_length=20, verbose_name='Tipo de Máquina')),
                ('tipo', models.IntegerField(blank=True)),
                ('perfil', models.CharField(max_length=20)),
                ('recurso', models.CharField(blank=True, max_length=20)),
                ('valor_tabela', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('proc_adicional', models.IntegerField(blank=True, default=0)),
                ('valor_proc_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('memoria_adicional', models.IntegerField(blank=True, default=0)),
                ('valor_memoria_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('disco_adicional', models.IntegerField(blank=True, default=0)),
                ('valor_disco_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('hosting_senai', models.BooleanField(blank=True, default=False, verbose_name='Hosting SENAI')),
                ('hosting_fieb', models.BooleanField(blank=True, default=False, verbose_name='Hosting FIEB')),
                ('data', models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.RenameField(
            model_name='hosting',
            old_name='data_delet',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='hosting',
            name='data_insert',
        ),
    ]
