# Generated by Django 2.2.3 on 2019-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0037_auto_20190731_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosting_deleted',
        ),
        migrations.RenameField(
            model_name='hosting',
            old_name='data',
            new_name='data_delet',
        ),
        migrations.AddField(
            model_name='hosting',
            name='data_insert',
            field=models.DateField(blank=True, default=None),
        ),
    ]
