# Generated by Django 2.2.3 on 2019-08-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0038_auto_20190731_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosting',
            old_name='data_delet',
            new_name='data_delete',
        ),
    ]
