# Generated by Django 2.2.3 on 2019-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0039_auto_20190801_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_dados',
            name='data_delete',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='backup_dados',
            name='data_insert',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='servicos_adicionais',
            name='data_delete',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='servicos_adicionais',
            name='data_insert',
            field=models.DateField(blank=True, default=None),
        ),
    ]
