# Generated by Django 2.2.3 on 2019-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0040_auto_20190802_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='perfil',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='tipo_maq',
            field=models.CharField(blank=True, default='Virtual', max_length=20, verbose_name='Tipo de Máquina'),
        ),
    ]
