# Generated by Django 2.2.3 on 2019-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0041_auto_20190806_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='hosting_fieb',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ambiente FIEB'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='hosting_senai',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ambiente SENAI'),
        ),
    ]
