# Generated by Django 2.2.3 on 2019-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0042_auto_20190806_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='cpu',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='disco',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='memoria',
            field=models.PositiveIntegerField(default=4, verbose_name='Memória'),
        ),
    ]
