# Generated by Django 2.2.3 on 2019-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0043_auto_20190806_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(blank=True, max_length=150)),
                ('qtd_uset', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='backup_dados',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
