# Generated by Django 2.2.3 on 2019-08-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0044_auto_20190814_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidades',
            old_name='qtd_uset',
            new_name='qtd_user',
        ),
    ]
